networks:
  my-app-network:  # Define the network name exactly as used later

services:
  postgres:
    image: postgres:16.1
    ports:
      - '5555:5432'
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_psw
    networks:
      - my-app-network  # Add the service to the network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@restaurant.com
      - PGADMIN_DEFAULT_PASSWORD=restaurant_password
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - 5050:80
    depends_on:
      - postgres
    user: root
    volumes:
      - postgres_data:/var/lib/pgadmin/data
    networks:
      - my-app-network  # Add the service to the network

volumes:
  postgres_data: