spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/restaurants'
    username: postgres
    password: postgres
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect